dock:
  x: -2.132
  y: 3.181
  z: 0.8022
  w: 0.5971
standby:
  x: -1.466
  y: 1.46
  z: 0.2285
  w: 0.9735
rooms:
  room1:
    hall:
      x: -1.474
      y: 3.329
      z: 0.1667
      w: 0.986
    inside:
      x: -0.25
      y: 3.738
      z: 0.1669
      w: 0.986
  room2:
    hall:
      x: -1.068
      y: 2.137
      z: 0.1568
      w: 0.9876
    inside:
      x: 0.117
      y: 2.662
      z: 0.1998
      w: 0.9798
  room3:
    hall:
      x: -0.609
      y: 1.041
      z: 0.1466
      w: 0.9892
    inside:
      x: 0.621
      y: 1.477
      z: 0.1688
      w: 0.9856
  room4:
    hall:
      x: -0.145
      y: -0.15
      z: 0.1648
      w: 0.9863
    inside:
      x: 0.904
      y: 0.275
      z: 0.1457
      w: 0.9893
