rooms:
  room1:
    hall:
      x: -0.326
      y: -0.754
      z: -0.7723
      w: 0.6353
    inside:
      x: -0.158
      y: -1.36
      z: -0.1137
      w: 0.9935
  room2:
    hall:
      x: 1.556
      y: -0.657
      z: -0.6164
      w: 0.7875
    inside:
      x: 1.558
      y: -1.299
      z: 0.9951
      w: -0.0985
  room3:
    inside:
      x: 1.669
      y: 1.32
      z: 0.9913
      w: 0.1313
  room4:
    hall:
      x: -0.1
      y: 0.537
      z: 0.7779
      w: 0.6284
    inside:
      x: -0.244
      y: 1.378
      z: 0.1182
      w: 0.993
