dock:
  x: -2.132
  y: 3.181
  z: 0.8022
  w: 0.5971
standby:
  x: -1.466
  y: 1.46
  z: 0.2285
  w: 0.9735
rooms:
  room1:
    hall:
      x: -1.769
      y: 3.227
      z: 0.1353
      w: 0.9908
    inside:
      x: -0.382
      y: 3.701
      z: 0.1018
      w: 0.9948
  room2:
    hall:
      x: -1.379
      y: 2.165
      z: 0.1595
      w: 0.9872
    inside:
      x: 0.177
      y: 2.756
      z: 0.168
      w: 0.9858
  room3:
    hall:
      x: -0.973
      y: 1.017
      z: 0.1763
      w: 0.9843
    inside:
      x: 0.561
      y: 1.588
      z: 0.1816
      w: 0.9834
  room4:
    hall:
      x: -0.626
      y: -0.218
      z: 0.149
      w: 0.9888
    inside:
      x: 0.882
      y: 0.315
      z: 0.2117
      w: 0.9773
labels:
  room1: 병실 101
  room2: 병실 102
  room3: 병실 103
  room4: 병실 104
  standby: 대기 장소
  dock: 충전 스테이션